services:
  edusms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusms
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - 3022:3000
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true