services:
  mariadb:
    image: mariadb:latest
    container_name: edusmsdb
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  dbview:
    depends_on:
      - mariadb
    image: adminer
    container_name: dbview
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - "8082:8080"

  edusms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusms
    restart: unless-stopped
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 120M
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 3022:3000