services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    command: --skip-grant-tables
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: paxxw0rd@2791
      MYSQL_DATABASE: edusms
      MYSQL_USER: lla
      MYSQL_PASSWORD: paxxw0rd@2791

  adminer:
    depends_on:
      - mariadb
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8082:8080

  edusms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusms
    restart: unless-stopped
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 120M
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 3022:3000
